config/routes.rb
ApiMashup::Application.routes.draw do
  root to: "challenges#index"
  get "/challenge", to: "challenges#show", as: "challenge"
  get "/login", to: "sessions#new"
  get "/apis/:id/mashups", to: "apis#mashups", as: "api_mashups"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/login", to: "sessions#new", as: "login"
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create, :show]
  resources :apis
  resources :mashups

  # get "/apis", to: "apis#index"
  # get "/apis/new", to: "apis#new"
  # get "/apis/:id", to: "apis#show"
  # post "/apis", to: "apis#create"
  # get "/mashups/:id", to: "mashups#show"
  # get "/mashups", to: "mashups#index"
  # get "/mashups/new", to: "mashups#new"
  # post "/mashups", to: "mashups#create"


end

app/models/api.rb
class Api < ActiveRecord::Base
  attr_accessible :name, :url, :description, :requires_key
  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true
  validates :requires_key, presence: true
  has_and_belongs_to_many :mashups
end

app/models/mashup.rb
class Mashup < ActiveRecord::Base
  attr_accessible :name, :url, :description
  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true
  has_and_belongs_to_many :apis
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  before_save :create_remember_token

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

	def create_remember_token
		self.remember_token = self.email + SecureRandom.urlsafe_base64
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
	skip_before_filter :authenticate, only: [:index, :show, :mashups]

	def index
		@apis = Api.all
		@apis.sort! {|a, b| a.name.downcase <=> b.name.downcase}
	end

	def show
		@api = Api.find(params[:id])
	end

	def new
		@api = Api.new(requires_key: "yes")
	end

	def create
		new_api = Api.create(params[:api])
		redirect_to new_api
	end

	def edit
		@api = Api.find(params[:id])
	end

	def update
		found_api = Api.find(params[:id])
		found_api.update_attributes(params[:api])
		redirect_to found_api
	end

	def destroy
		Api.delete(params[:id])
		redirect_to apis_path
	end

	def mashups
		@api = Api.find(params[:id])
		@mashups = @api.mashups
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  before_filter :authenticate
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	skip_before_filter :authenticate, only: [:index, :show]
	include ChallengesHelper

	def index
	end

	def show
		@level = 2
		@apis = []
		@api_ids = ""

		# level allows for future feature of user selecting how many random APIs to return
		until @apis.count == @level

			# choose a random number and find the api id of that array index
			random_api = Api.all.sample

			# if the api isn't already included in the array, add it
			# also, add it to the params string to pass to the new mashup page for pre-selection
			unless @apis.include?(random_api)
				@apis << random_api
				@api_ids += random_api.id.to_s
			end

			# if the api isn't the last one in the array, add a dash after it
			# the dashes are used on the new mashups page to split the api ids
			@api_ids += "-" if @apis.count < @level

		end

		# create some fun random names for the mashup
		partial_string1 = @apis[0].name[0..@apis[0].name.length/2]
		partial_string2 = @apis[1].name[@apis[1].name.length/2..@apis[1].name.length]
		@mashup1 = partial_string1 + partial_string2

		partial_string3 = @apis[1].name[0..@apis[1].name.length/2]
		partial_string4 = @apis[0].name[@apis[0].name.length/2..@apis[0].name.length]
		@mashup2 = partial_string3 + partial_string4

		@mashup_names = mash_names(@apis)


	end
end

app/controllers/mashups_controller.rb
class MashupsController < ApplicationController
	skip_before_filter :authenticate, except: [:edit, :update, :destroy]

	def index
		@mashups = Mashup.all
	end

	def show
		@mashup = Mashup.find(params[:id])

	end

	def new
		@mashup = Mashup.new
		apis = Api.all
		@api_list = []
		apis.each do |api|
			@api_list << [api.name, api.id]
		end

		@api_list.sort! {|a, b| a[0].downcase <=> b[0].downcase}

		if params[:apis]
			@selected = params[:apis].split("-").map{ |id| id.to_i }
		end

	end

	def create
		new_mashup = Mashup.create(params[:mashup])
		
		selected_apis = params[:api_id]
		apis = []
		selected_apis.each do |id|
			apis << Api.find(id)
		end

		new_mashup.apis << apis

		redirect_to new_mashup
	end

	def edit
		@mashup = Mashup.find(params[:id])

		apis = Api.all
		@api_list = []
		apis.each do |api|
			@api_list << [api.name, api.id]
		end

		@selected = []
		selected_apis = @mashup.apis
		selected_apis.each do |api|
			@selected << api.id
		end

	end

	def update
		# find mashup and update basic attributes (name, url, description)
		found_mashup = Mashup.find(params[:id])
		found_mashup.update_attributes(params[:sample])

		selected_apis = params[:api_id]
		# selected_apis.map!{|api| api.to_i }
		
		# create array of existing api_ids based on join record
		existing_apis = []
		found_mashup.apis.each do |api|
			existing_apis << api.id
		end

		# compare existing apis to those selected on the form
		# if selected_apis includes an existing_api, do nothing and remove it from the selected_apis list
		# if selected_apis does not include existing_api, remove the join record and remove it from the selected_apis list
		existing_apis.each do |api|
			if selected_apis.include?(api)
				selected_apis.pop
			else 
				found_mashup.apis.delete(Api.find(api))
			end
		end

		# Any leftover apis in the list are new records. Create them
		selected_apis.each do |api|
			found_mashup.apis << Api.find(api)
		end

		redirect_to found_mashup
	end

	def destroy
		Mashup.delete(params[:id])
		redirect_to mashups_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authenticate, only: [:new, :create]

	def new

	end

	def create
		user = User.find_by_email(params[:user][:email])
		if user && user.authenticate(params[:user][:password])
			sign_in(user)
			redirect_to user
		else
			redirect_to "/login"
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end


	def create
		@new_user = User.create(params[:user])
		sign_in(@new_user)

		redirect_to root_path
	end

	def show
		@user = User.find(params[:id])
	end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
	def mash_names(apis)
		names = []
		case apis.count
		when 2 then
			names << @apis[0].name[0..@apis[0].name.length/2] + @apis[1].name[@apis[1].name.length/2..@apis[1].name.length]
			names << @apis[1].name[0..@apis[1].name.length/2] + @apis[0].name[@apis[0].name.length/2..@apis[0].name.length]
		when 3 then
			names << @apis[0].name[0..@apis[0].name.length/3] + @apis[1].name[@apis[1].name.length/3..(@apis[1].name.length/3)*2] + @apis[2].name[(@apis[2].name.length/3)*2..@apis[2].name.length]
			names << @apis[1].name[0..@apis[1].name.length/3] + @apis[2].name[@apis[2].name.length/3..(@apis[2].name.length/3)*2] + @apis[0].name[(@apis[0].name.length/3)*2..@apis[0].name.length]
			names << @apis[2].name[0..@apis[2].name.length/3] + @apis[0].name[@apis[0].name.length/3..(@apis[0].name.length/3)*2] + @apis[1].name[(@apis[1].name.length/3)*2..@apis[1].name.length]
		end
	end
end

app/helpers/mashups_helper.rb
module MashupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def authenticate
		redirect_to "/login" if !current_user
	end

	def sign_out
		@current_user = nil
		cookies.delete(:remember_token)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apis/_apis-form.html.erb
<%= form_for @api, html: {role: "form"} do |f| %>
  <div class="form-group">
		<label for="name">Name of the API</label>
		<%= f.text_field :name, required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<label for="url">URL for API dev tools</label>
		<%= f.text_field :url, required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<label for="key">Is a developer key required?</label>
		<div class="radio">
		  	<%= radio_button("api", "requires_key", "yes") %>
		  	<%= label_tag(:requires_key_yes, "Yes, a developer key is required") %>
		</div>
		<div class="radio">
			<%= radio_button("api", "requires_key", "no") %>
			<%= label_tag(:requires_key_yes, "No, a developer key is not required") %>
		</div>
	</div>
	<div class="form-group">
		<label for="description">API description (features, available parameters, etc.)</label>
		<%= f.text_area :description, required: true, class: "form-control", rows: "5" %>
	</div>
	<%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/apis/edit.html.erb
<h2 class="page-header text-center">Edit API</h2>
<%= render "apis-form" %>

app/views/apis/index.html.erb
<% if current_user %>	
	<ul class="nav nav-pills pull-right">
		<li><%= link_to "New", new_api_path %></li>
	</ul>
<% end %>
<h2 class="page-header text-center">APIs</h2>
<table class="table table-hover">
	<thead>
		<th>Name</th>
		<th>URL</th>
		<th>Mashups</th>
	</thead>
	<tbody>
	<% @apis.each do |api| %>
		<tr>
			<td><%= link_to api.name, api_path(api) %></td>
			<td><%= link_to api.url, api.url%></td>
			<td><%= api.mashups.count %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/apis/mashups.html.erb
<h2 class="page-header text-center">Mashups using <%= @api.name %></h2>
<%= render "mashups/mashups-table" %>

app/views/apis/new.html.erb
<h2 class="page-header text-center">Add API</h2>
<%= render "apis-form" %>

app/views/apis/show.html.erb
<% if current_user %>
	<ul class="nav nav-pills pull-right">
		<li><%= link_to "Edit",  edit_api_path(@api) %></li>
		<li><%= link_to "Delete",  api_path(@api), method: :delete %></li>
	</ul>
<% end %>

<h2 class="page-header text-center"><%= @api.name %></h2>

<p><%= simple_format(@api.description) %></p>

<table class="table table-hover table-bordered">
	<thead>
		<th colspan=2 >API Info</th>
	</thead>
	<tbody>
		<tr>
			<td>Mashups:</td>
			<td><%= link_to "#{@api.mashups.count} mashups made with this API", api_mashups_path(@api) %></td>
		</tr>
		<tr>
			<td>API homepage:</td>
			<td><%= link_to @api.url, @api.url %></td>
		</tr>
		<tr>
			<td>Developer key required:</td>
			<td><%= @api.requires_key.capitalize %></td>
		</tr>
	</tbody>
</table>

app/views/challenges/index.html.erb
<div class="jumbotron text-center">
	<h2>API Mashup Challenge</h2>
	<p>Do you have what it takes to accept the challenge?</p>
	<h2><%= link_to "Challenge me!", challenge_path, class: "btn btn-primary btn-lg"%></h2>
</div>

<p>We've all been there. You're itching to work on a new project, but fresh out of ideas. What should you spend your Saturday night hacking away at? <%= link_to "Try one of our challenges!", challenge_path %></p>
<p>Once you've built out your app, don't forget to <%= link_to "share it.", new_mashup_path %> Show off your rad mashup skills.</p>
<h5>Good luck, coders!</h5>

app/views/challenges/show.html.erb
<div class="jumbotron text-center">
	<h4>Create "<%= @mashup1 %>" or "<%= @mashup2 %>" using</h4>
		<% @apis.each do |api| %>
			<h2><%= api.name %></h2>
			<% unless api == @apis.last %>
				<h2>&</h2>
			<% end %>
		<% end %>
	<div class="row">
		<div class="col-md-6">
			<h2>
				<%= link_to "Challenge accepted!", new_mashup_path(apis: @api_ids), class: "btn btn-success btn-lg btn-block" %>
			</h2>
		</div>
		<div class="col-md-6">
			<h2>
				<%= link_to "I'm not worthy!", challenge_path, class: "btn btn-danger btn-lg btn-block"%>
			</h2>
		</div>
	</div>
<!-- 	<div class="row">
		<h5 class="text-muted">APIs per challenge</h5>
		<div class="btn-group">
		  <button type="button" class="btn btn-default">1</button>
		  <button type="button" class="btn btn-default">2</button>
		  <button type="button" class="btn btn-default">3</button>
		  <button type="button" class="btn btn-default">4</button>
		  <button type="button" class="btn btn-default">5</button>
		</div>
	</div> -->
</div>

<p>Need some info before making a decision? Here's some quick stats about the APIs</p>
<table class="table table-hover">
	<thead>
		<th></th>
		<% @apis.each do |api| %>
			<th><%= api.name %></th>
		<% end %>
	</thead>
	<tbody>
		<tr>
			<td>API Homepage:</td>
			<% @apis.each do |api| %>
				<td><%= link_to api.url, api.url, target: "_blank" %></td>
			<% end %>
		</tr>
		<tr>
			<td>Developer key required:</td>
			<% @apis.each do |api| %>
				<td><%= api.requires_key.capitalize %></td>
			<% end %>
		</tr>
		<tr>
			<td>Mashups:</td>
			<% @apis.each do |api| %>
				<td><%= link_to "#{api.mashups.count} mashups with this API", api_mashups_path(api.id), target: "_blank" %></td>
			<% end %>
		</tr>
	</tbody>
</table>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="nav-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">API Mashup Challenge</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "APIs", apis_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mashups <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View", mashups_path %></li>
            <li><%= link_to "Add", new_mashup_path %></li>
          </ul>
        </li>
        <li><%= link_to "New Challenge", challenge_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_simple-nav.html.erb
<header class="page-header">
  <ul class="nav nav-pills pull-right">
    <li><%= link_to "APIs", apis_path %></li>
    <li><%= link_to "Mashups", mashups_path %></li>
    <li><%= link_to "Add Mashup", new_mashup_path %></li>
  </ul>
  <h3 class="text-muted">API Mashup Challenge</h3>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiMashup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/nav" %>
	<div class="container">
			<%= yield %>
	</div>
	<footer>
		<p class="text-right">
			<% if current_user %>
				<%= link_to "Logout", logout_path %>
			<% else %>
				<%= link_to "Admin", login_path %>
			<% end %>
		</p>
	</footer>

</body>
</html>

app/views/mashups/_mashups-form.html.erb
<%= form_for @mashup, role: "form" do |f| %>
  <div class="form-group">
		<label for="name">Name</label>
		<%= f.text_field :name, required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<label for="url">URL</label>
		<%= f.url_field :url, required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<label for="apis">APIs used</label>
		<%= select_tag(:api_id, options_for_select(@api_list, selected: @selected), id: "multi-select", multiple: true, include_blank: true) %>
	</div>
	<div class="form-group">
		<label for="description">Description</label>
		<%= f.text_area :description, required: true, class: "form-control", rows: "5" %>
	</div>
	<%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/mashups/_mashups-table.html.erb
<table class="table table-hover">
	<thead>
		<th>Name</th>
		<th>URL</th>
		<th>APIs Used</th>
	</thead>
	<tbody>
	<% @mashups.each do |mashup| %>
		<tr>
			<td><%= link_to mashup.name, mashup_path(mashup) %></td>
			<td><%= link_to mashup.url, mashup.url%></td>
			<td><%= mashup.apis.count %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/mashups/edit.html.erb
<h2 class="page-header text-center">Edit Mashup</h2>
<%= render "mashups-form" %>

app/views/mashups/index.html.erb
<% if current_user %>
	<ul class="nav nav-pills pull-right">
		<li><%= link_to "New", new_mashup_path %></li>
	</ul>
<% end %>
<h2 class="page-header text-center">Mashups</h2>
<%= render "mashups-table" %>

app/views/mashups/new.html.erb
<h2 class="page-header text-center">Add Mashup</h2>
<%= render "mashups-form" %>

app/views/mashups/show.html.erb
<% if current_user %>
	<ul class="nav nav-pills pull-right">
		<li><%= link_to "Edit",  edit_mashup_path(@mashup) %></li>
		<li><%= link_to "Delete",  mashup_path(@mashup), method: :delete %></li>
	</ul>
<% end %>

<h2 class="page-header text-center"><%= @mashup.name %></h2>
<p><%= link_to @mashup.url, @mashup.url %></p>
<p><%= simple_format(@mashup.description) %></p>

<table class="table table-hover table-bordered">
	<thead>
		<th colspan=2 >APIs Used</th>
	</thead>
	<tbody>
		<% @mashup.apis.each do |api| %>
		<tr>
			<td><%= link_to api.name, api_path(api) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<h2 class="page-header text-center">Add User</h2>

<form action="/users" method="post" role="form">
	<div class="form-group">
		<input type="text" placeholder="name" name="user[name]" class="form-control"/>
	</div>
	<div class="form-group">
		<input type="text" placeholder="email" name="user[email]" class="form-control"/>
	</div>
		<input type="password" placeholder="password" name="user[password]" class="form-control"/>
	<div class="form-group">
	</div>
	<div class="form-group">
		<input type="password" placeholder="confirm password" name="user[password_confirmation]" class="form-control" />
	</div>
	<input type="submit" value="submit" class="btn btn-primary" />
</form>

app/views/users/show.html.erb
<h2 class="page-header text-center">Welcome, <%= @user.name %></h2>
<ul>
	<li><%= link_to "Add API", new_api_path %></li>
	<li><%= link_to "Add mashup", new_mashup_path %></li>
	<li><%= link_to "Add user", new_user_path %></li>
</ul>